version: '3.7'
services:
  chipper:
    build: .
    entrypoint:
      - "/chipper"
      - "start"
    environment: 
      - DDL_RPC_PORT=${DDL_RPC_PORT}
      - DDL_RPC_INSECURE=${DDL_RPC_INSECURE}
      - DDL_RPC_TLS_CERTIFICATE=${DDL_RPC_TLS_CERTIFICATE}
      - DDL_RPC_TLS_KEY=${DDL_RPC_TLS_KEY}
      - DDL_RPC_CLIENT_AUTHENTICATION=${DDL_RPC_CLIENT_AUTHENTICATION}
    expose:
      - "8084"
    ports:
      - "8084:8084"